### ISSUE TITLE
[BUG] The picture field is lost after the collection is exported

### ISSUE THREAD

**Issue by guoduhw** [Baboo7/strapi-plugin-import-export-entries#73]
Create a collection in the content type builder. The collection contains media fields, and then maintain the content in the content manager. Then use the import and export plug-ins to export the collection. After exporting, it is found that the media fields are lost. Can you repair and find a bug as soon as possible? Because the import and export collection function is very meaningful, thank you!

**Comment by sharkfin009** [comment]
When you say the images are lost , do you mean you are importing the file that you exported into another strapi application? Because that would mean that the images files dont exist in that application, and that means that the ids which refer to the images in the original application dont refer to anything in the new application. If what I described is your situation, you need to import a file with the media fields containing urls and no ids. The plugin has code which then imports the image files using the url, and creates a new entry in the database for it with a new id. If you want help from me, no problem
