### ISSUE TITLE
[BUG] Quick Actions > Importing a Quick Actions Export, ID option field dropdown is empty

### ISSUE THREAD

**Issue by JWesorick** [Baboo7/strapi-plugin-import-export-entries#79]
**Describe the bug**

**To Reproduce**

1. With `1.18.0`, go to "Quick Actions" > "Export".
2. Download export file.
3. Try to import the file just created with "Quick Actions" > "Import".
4. Under "Options" tab, "Id Field" drop-down has no options.

**Expected behavior**

**Screenshots**
![Screen Shot 2022-11-11 at 2 38 12 PM](https://user-images.githubusercontent.com/801062/201290911-062ee9d6-27e2-4d89-85e8-a11b3ed443d7.png)

**Additional context**

**Comment by Baboo7** [comment]
That's a good point. I should have hidden the dropdown since it's not relevant when importing the whole database. When importing whole database, the id field is applied to every collection specified in the file. Since there are very few chances for an id field other than `id` to be relevant for every collection, it is not possible atm to specify it.
