### ISSUE TITLE
[FEATURE] Import/Export API

### ISSUE THREAD

**Issue by sargreal** [Baboo7/strapi-plugin-import-export-entries#8]
**Is your feature request related to a problem? Please describe.**
When migrating from another platform to strapi, one often has multiple content types that need to be imported. It would be awesome if this plugin would support doing that automated.

**Describe the solution you'd like**
Importing should be possible by calling an api endpoint (without the necessity of content-manager permissions but rather just the normal users-permissions plugin for which then a read/write api token could be used) and even better a service that could be called from a startup script or anything similar.

Also a guide on how to do this would be fitting in the Readme.

**Describe alternatives you've considered**
- Manually importing all is tedious
- Writing the imports directly is possible, but that is actually already implemented here - only the interface is missing

**Additional context**
The way it is currently implemented with the import happening only in the controllers is actually also against how the plugin structure should be I think, as in controllers are for managing access and services should be for actually executing the action. But that is probably up for debate

**Comment by Baboo7** [comment]
I agree the import logic should be moved to a service. And I think this could be a quick win for the use case your mentioning, since it would be possible to write a script to automate imports (the export endpoint already exists). What do you think?

About using the users-permissions auth, I feel this could be a security breach if misconfigured by the user.
Creating a role with only read permissions (content-manager) gives a better control on who can access what and permissions can be revoked fast and easily.

**Comment by Baboo7** [comment]
I just published version `1.5.0`.
Doc now explain [how to use the `import` service](https://github.com/Baboo7/strapi-plugin-import-export-entries#services).

**Comment by Baboo7** [comment]
Version `1.9.0` is out. Importing/exporting data is now possible through the content api
See the [Content API](https://github.com/Baboo7/strapi-plugin-import-export-entries#content-api) section of the doc for usage
