### ISSUE TITLE
[BUG] Data is getting duplicated when modifying the content after importing data in a repeatable component

### ISSUE THREAD

**Issue by manikanta47052** [Baboo7/strapi-plugin-import-export-entries#91]
**Data is getting duplicated when modifying the content after importing data in a repeatable component**

**To Reproduce**

1. I have a repeatable component with two fields label and url, I created a single collection type 'Test' with two of these repeatable component like below.
![image](https://user-images.githubusercontent.com/122001914/211022621-7b3a8c07-1a48-42d9-80d3-5ae9dd7ceb67.png)
2. I have two different workspaces with same content type Test. One workspace is for exporting content and another workspace for importing the content file
3. After adding content in 1st workspace and exporting it.
Importing the exported content file in a 2nd workspace with same Test content type and it is getting successfully saved

![image](https://user-images.githubusercontent.com/122001914/211023823-78145f01-19c9-4685-8d80-24f296f8d291.png)

4. After refreshing the page and trying to modifying or adding new data to the imported content
![image](https://user-images.githubusercontent.com/122001914/211024793-f1e8e48c-b1cf-41c9-87aa-6e05b885364c.png)

5. After clicking save the data is getting duplicated like below and also not able to delete duplicated content
![image](https://user-images.githubusercontent.com/122001914/211026258-17e75718-4122-4b0a-8e34-3c502695a7be.png)

**Expected behavior**
After modifying the imported content, The content should not be duplicated in repeatable component

**Additional context**
I tried to use strapi unique field option but there is a bug in strapi that is not letting me add new data even though content is unique

Im new to this. Let me know if there is anything im missing. 
Really appreciate your work, this plugin is very useful. Thanks in advance.

**Comment by LiquidITGuy** [comment]
We have the same behaviour here.
putting a flag on this topic.

**Comment by meganoob1337** [comment]
I have had this problem aswell, 
My workaround is now:
Import your Data (i used it to migrate from another system and generate the import files and add the assets as the upload is nice) 
then use the new Feature in strapi v4.6.0 and export your content with yarn strapi export 
then reset the DB 
then import your exported data with yarn strapi import -f <filename that was generated> 
Now i dont have the problem with duplication anymore (I have no clue why, but im happy - took me forever to migrate everything into the json format for importexport entries plugin )
Hope this helps and works for you as well :) @manikanta47052  @LiquidITGuy

**Comment by tcherokee** [comment]
Same here. Going to try @meganoob1337 solution....

**Comment by anujkohli** [comment]
I am facing the same issue, can this be fixed please?

**Comment by mitenka** [comment]
It looks like issue #81 has similar nature. And I hope that PR #97 fixes it. It's not covered with tests tho, feel free to propose improvements and share if it works for you

**Comment by Kyle772** [comment]
https://discord.com/channels/1021121498276171786/1021121949537153145/1049829680573849661

A user on the discord channel has figured out a work around until this is fixed

Here are the steps:
1) Run an import
2) Query through the db with pgadmin or another db management tool
3) Anything that ends in "_components" is a culprit
4) Look for component_type === null
5) Grab the value from the attributes.<name>.component key in each of your strapi schemas 
6) do a bulk update on all component_types that are null and set it to the value from step 5
6.5) If you run into errors on placing values it's due to you already having duplicate entries in your db, I was safely able to just delete the duplicates (since the data is in the component_type null entries already). If you rerun a fresh import this can be avoided.
7) repeat through all "_component" tables
8) Backup your db once you've done them all so you have a checkpoint.

**Comment by Baboo7** [comment]
Thank you for this detailed report folks! Checkout version 1.19.0 that fixes the issue
