### ISSUE TITLE
[QUESTION] Is this plugin still maintained?

### ISSUE THREAD

**Issue by lsagetlethias** [Baboo7/strapi-plugin-import-export-entries#93]
**Context**
I see a lot of similar issues around importing datas with v2 format and about multiplied values.
Importing entries with recursive relations is not doable because of validation.
Also, exporting full db is available, but importing back this same "full db" is not available.
Finally, JSON and CSV export are now flagged as deprecated ; so what now?

**Comment by victazzz** [comment]
@Baboo7

**Comment by josephpage** [comment]
The answer is yes.
The maintainer merged my PR #98 that fixed an incompatibility with the newest Strapi versions and made some maintenance commits.

**Comment by lsagetlethias** [comment]
Well, a merge does only mean that maintainers would accept contributions, not that they will fix major bugs or handle updates themselves.

**Comment by Baboo7** [comment]
@lsagetlethias I'm still maintaining the project. I had very few time available the past few months since we were fundraising in the company I'm working in.

To give you some context, importing data is not as easy as it seems. There is a lot of features to take into account and most of the time the way the entity service and the query api work are not documented. Some excavations are required to understand strapi's implementation and this archeology is time consuming. Join the [Discord Community](https://discord.gg/dcqCAFFdP8) to get the latest updates

**Comment by Baboo7** [comment]
I'm closing this issue so it won't make people think this plugin is not maintained
